- gliner/model.py
- gliner/modules/evaluator.py
Previous output sample: [{'start': 1, 'end': 36, 'text': 'Cristiano Ronaldo dos Santos Aveiro', 'label': 'person'}]
New output sample: [{'start': 1, 'end': 36, 'text': 'Cristiano Ronaldo dos Santos Aveiro', 'label': 'person', 'score': 0.8832555413246155}]
> Adding score in the model output

- gliner/model.py
- gliner/modules/token_splitter.py
- gliner/modules/tokenizer.py
**Summary of Changes:**
We have introduced a new tokenization method based on morpheme analysis to improve the accuracy of the Korean Named Entity Recognition (NER) model. This addition complements the existing space-based tokenization (WhitespaceTokenizer) with a new class MecabKoTokenizer, utilizing the Mecab morpheme analyzer.
**Configuration Settings:**
gliner_config.json: This JSON file allows users to configure the tokenizer settings. The tokenizer field within this file can be used to specify the tokenizer. If no tokenizer is set, the WhitespaceTokenizer is used by default.
**Testing Information:**
Testing for the Korean NER model can be done using the model available at [taeminlee/gliner_ko](https://huggingface.co/taeminlee/gliner_ko). The gliner_config.json in that repository is …
> Addition of Morpheme-based Tokenization for Korean NER

- examples/finetune.ipynb
- gliner/__init__.py
- gliner/model.py
- gliner/trainer.py
- requirements.txt
Hi,
I've created a trainer class that has support for:
- Accelerate which enables mixed precision training (fp16, bf16 or fp8).
- Gradient Accumulation, which enables you to train faster and with a bigger effective batch size.
- Train using total of epochs or steps
- Checkpoints every X epoch/steps
- Evaluation every X steps
I used the trainer in https://github.com/lucidrains/meshgpt-pytorch as a boilerplate, so credits to @lucidrains for the nicely structured trainer.
> Implementation of trainer class (fp16 training & gradient accumulation)

- gliner/model.py
Fix for the issue reported [here](https://github.com/urchade/GLiNER/issues/91#issuecomment-2118672273)
> fix for SimpleNamespace is not JSON serializable

- config.yaml
- gliner/model.py
- gliner/modules/layers.py
- gliner/modules/loss_functions.py
- gliner/modules/span_rep.py
- train.py
Overall, it was generalised training by the following changes:
- Switched to focal loss instead of binary cross-entropy loss and constant weighting. With specific parameters of focal loss, it will become binary cross-entropy; in this case, alpha and gamma should be equal to 0;
- Added more scheduler types, like linear, polynomial, constant;
- Added support of different weight decays for the encoder and other components of a model;
> Generalize training

- config.yaml
- config_span.yaml
- config_token.yaml
- gliner/__init__.py
- gliner/model.py
- gliner/modules/base.py
- gliner/modules/data.py
- gliner/modules/data_proc.py
- gliner/modules/layers.py
- gliner/modules/loss_functions.py
- train.py
1. *Computes scores for the start, end, and inside positions of potential entity spans.*:
```python
scores_start, scores_end, scores_inside = self.compute_score_eval(x)
```
2. *Converts these scores into probabilities and determines start and end positions where probabilities exceed a specified threshold.*:
```python
start_probs = torch.sigmoid(scores_start)
end_probs = torch.sigmoid(scores_end)
inside_probs = torch.sigmoid(scores_inside)
start_indices = [torch.where(start_probs[i] > threshold) for i in range(len(x["tokens"]))]
end_indices = [torch.where(end_probs[i] > threshold) for i in range(len(x["tokens"]))]
```
3. *Match Start and End Indices to Create Valid Spans and ensures class label consistency and filters out low-confidence spans based on the inside scores.*:
```python …
```
> Add Token-level GLiNER

- gliner/model.py
prevent errors when entity exceed sequence length
> fix out of bounds

- README.md
- train.py
1. Created a Trainer class for better flexibility;
2. Added support of  Distributed Data Parallel mode;
3. Updated readme adding information about the multi-task model;
> Distributed Data Parallel mode support

- config.yaml
- config_span.yaml
- config_token.yaml
- gliner/model.py
- gliner/modules/loss_functions.py
- train.py
- train_multi_gpu.py
It was added a new parameter to the loss function - label smoothing. It can be beneficial, especially in the case of synthetic datasets, where quality can be insufficient.
> Add label smoothing

- gliner/data_processing/dataset.py
Addressing #127 by enforcing data type.
> fix sample error

- gliner/data_processing/tokenizer.py
Add Chinese language tokenizers: Jieba and HanLP
- Implement two tokenizers for improved Chinese NER:
1. Jieba: Fast but less accurate
2. HanLP: Slower but significantly more accurate
- Enhance NER results by addressing Chinese language tokenization challenges
> Add Jieba and HanLP for Chinese sentence tokenization.

- gliner/data_processing/processor.py
add negative entities manually
> manual negatives

- RELEASE.md
- gliner/evaluation/evaluator.py
- pyproject.toml
- requirements.txt
This PR relates to the following issue: https://github.com/urchade/GLiNER/issues/137
Dependency seqeval is now removed and the logic that was used to have a safe divide by zero operation has been moved into evaluation.
> Removed outdated dependency and ported divide by zero logic

- gliner/model.py
This PR adds the session_options parameter to the _from_pretrained method.
> add session options to _from_pretrained method

- gliner/model.py
Fix the bug when running the training with `load_best_model_at_end=True`
```
AttributeError: 'GLiNER' object has no attribute '_keys_to_ignore_on_save'
```
> Fix load checkpoint

- gliner/config.py
- gliner/model.py
- gliner/modeling/base.py
- gliner/modeling/encoder.py
* Add new entity representation schema for better support of other models;
* Adapt GLiNER for modern LLMs as backbones;
* Add support of T5 encoder as a backbone;
> Add support of modern decoders as a backbone

- gliner/model.py
Realize `batch_predict_entities` with the torch.DataLoader for more efficient preprocessing.
> improve batch processing for inference

- gliner/multitask/classification.py
Fixes #227 by adding an additional elif condition
> Fix bug in text classification evaluation

- README_Extended.md
> docs: update README_Extended.md

- configs/config.yaml
- gliner/modeling/base.py
- gliner/modeling/loss_functions.py
- gliner/training/trainer.py
- train.py
It was added a probability margin, creating an option to turn the focal loss function to asymmetric, as it was introduced in the paper: [Asymmetric Loss For Multi-Label Classification](https://arxiv.org/abs/2009.14119) .
> Implement Assymetric loss
